version: '3.0'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-ui
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/dashboards
    ports:
      - "3000:3000"
    networks:
      - monitoring

  alloy:
    image: docker.io/grafana/alloy:latest
    container_name: grafana-alloy
    restart: unless-stopped
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - "./config/alloy/config.alloy://etc/alloy/config.alloy"
      - "/var/run:/var/run:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    networks:
      - monitoring

  mimir:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir-config/mimir.yml"]
    container_name: grafana-mimir
    restart: unless-stopped
    volumes:
      - ./config/mimir.yml:/etc/mimir-config/mimir.yml
    expose:
      - 9009
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: grafana-loki
    restart: unless-stopped
    volumes:
      - loki_data:/loki
    expose:
      - 3100
    networks:
      - monitoring
      - loki

volumes:
  grafana_data: {}
  promtail_data: {}
  loki_data: {}

networks:
  monitoring:
    driver: bridge
  loki:
    driver: bridge
