version: '3.0'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-ui
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/dashboards
    ports:
      - "3000:3000"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: grafana-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  container-exporter:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: grafana-container-exporter
    restart: unless-stopped
    privileged: true
    devices:
     - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    expose:
      - 8080
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: grafana-promtail
    restart: unless-stopped
    volumes:
      - ./config/pomtail.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - promtail_data:/data
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: grafana-prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: grafana-loki
    restart: unless-stopped
    volumes:
      - loki_data:/loki
    expose:
      - 3100
    networks:
      - monitoring
      - loki

volumes:
  prometheus_data: {}
  grafana_data: {}
  promtail_data: {}
  loki_data: {}

networks:
  monitoring:
    driver: bridge
  loki:
    driver: bridge
