version: '3.0'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-ui
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/dashboards
    ports:
      - "3000:3000"
    networks:
      - monitoring

  agent:
    image: grafana/agent:main
    container_name: grafana-agent
    restart: unless-stopped
    entrypoint:
      - /bin/grafana-agent
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/agent/agent.river
    environment:
      AGENT_MODE: "flow"
    volumes:
      - ./config/agent.river:/etc/agent/agent.river
      - /var/run:/var/run:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    expose:
      - 12345
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: grafana-promtail
    restart: unless-stopped
    volumes:
      - ./config/pomtail.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - promtail_data:/data
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: grafana-prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring

  mimir:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir-config/mimir.yml"]
    container_name: grafana-mimir
    restart: unless-stopped
    volumes:
      - ./config/mimir.yml:/etc/mimir-config/mimir.yml
    expose:
      - 9009
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: grafana-loki
    restart: unless-stopped
    volumes:
      - loki_data:/loki
    expose:
      - 3100
    networks:
      - monitoring
      - loki

volumes:
  prometheus_data: {}
  grafana_data: {}
  promtail_data: {}
  loki_data: {}

networks:
  monitoring:
    driver: bridge
  loki:
    driver: bridge
