global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "salih_local"
    scrape_interval: 5s
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
      - targets: ['container-exporter:8080']