apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    basicAuth: false
    url: http://loki:3100
    jsonData:
      maxLines: 1000
  - name: Mimir
    type: prometheus
    uid: mimir
    access: proxy
    orgId: 1
    url: http://mimir:9009/prometheus
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      timeInterval: '1m'
